"""myfiles

Revision ID: bf74339902fd
Revises: 599117057e28
Create Date: 2017-01-10 16:17:32.374682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf74339902fd'
down_revision = '599117057e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imprts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('myfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('1', '2', '3'), nullable=True),
    sa.Column('imported_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('imported_from_path', sa.String(length=512), nullable=True),
    sa.Column('imprt_id', sa.Integer(), nullable=True),
    sa.Column('_preview', sa.String(length=512), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['imprt_id'], ['imprts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('myfiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_myfiles_hash'), ['hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myfiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_myfiles_hash'))

    op.drop_table('myfiles')
    op.drop_table('imprts')
    # ### end Alembic commands ###
